export const currencyColors = {
    "AFN" : {"color" : "#ead1c8", "explanation" : "Afghan Afghani"},
    "ALL" : {"color" : "#c5c0d0", "explanation" : "Albanian Lek"},
    "DZD" : {"color" : "#dbeae6", "explanation" : "Algerian Dinar"},
    "AOA" : {"color" : "#9b93a1", "explanation" : "Angolan Kwanza"},
    "ARS" : {"color" : "#f0d2aa", "explanation" : "Argentine Peso"},
    "AMD" : {"color" : "#b0afb6", "explanation" : "Armenian Dram"},
    "AWG" : {"color" : "#dcc6c9", "explanation" : "Arubian Florin"},
    "AUD" : {"color" : "#c2b798", "explanation" : "Australian Dollar"},
    "AZN" : {"color" : "#E3D9B3", "explanation" : "Azerbaijani Manat"},
    "BSD" : {"color" : "#d2bbba", "explanation" : "Bahamian Dollar"},
    "BHD" : {"color" : "#aaa3a1", "explanation" : "Bahrain Dinar"},
    "BDT" : {"color" : "#938a94", "explanation" : "Bangladeshi Taka"},
    "BIF" : {"color" : "#D7C6D3", "explanation" : "Burundian Franc"},
    "VUV" : {"color" : "#89b499", "explanation" : "Vanuatu Vatu"},
    "BBD" : {"color" : "#cac7b8", "explanation" : "Barbados Dollar"},
    "BYN" : {"color" : "#9ca982", "explanation" : "Belarusian Ruble"},
    "BZD" : {"color" : "#ccb8ac", "explanation" : "Belize Dollar"},
    "BMD" : {"color" : "#b8c0b6", "explanation" : "Bermuda Dollar"},
    "BTN" : {"color" : "#e6d08d", "explanation" : "Bhutanese Ngultrum"},
    "BOB" : {"color" : "#d8c7ad", "explanation" : "Bolivian Boliviano"},
    "BAM" : {"color" : "#e0c7c8", "explanation" : "Bosnian Convertible Mark"},
    "BWP" : {"color" : "#a09da0", "explanation" : "Botswana Pula"},
    "BRL" : {"color" : "#b8cdce", "explanation" : "Brazilian Real"},
    "BND" : {"color" : "#a9a6a0", "explanation" : "Brunei Dollar"},
    "BGN" : {"color" : "#e7e2d3", "explanation" : "Bulgarian Leva"},
    "BUK" : {"color" : "#b9c6c8", "explanation" : "Burmese Kyat"},
    "KHR" : {"color" : "#a2afa5", "explanation" : "Cambodian Riel"},
    "CVE" : {"color" : "#dcd1b9", "explanation" : "Cape Verdean Escudo"},
    "KYD" : {"color" : "#b7a998", "explanation" : "Cayman Islands Dollar"},
    "XAF" : {"color" : "#cac0c5", "explanation" : "CFA Franc"},
    "XPF" : {"color" : "#EEDFCA", "explanation" : "CFP Franc"},
    "CLP" : {"color" : "#b5c9db", "explanation" : "Chilean Pesos"},
    "CNY" : {"color" : "#f2cccd", "explanation" : "Chinese Yuan"},
    "COP" : {"color" : "#bcc9c8", "explanation" : "Colombian Peso"},
    "KMF" : {"color" : "#dfb56e", "explanation" : "Comorian Franc"},
    "CDF" : {"color" : "#90a994", "explanation" : "Congolese Franc"},
    "CRC" : {"color" : "#d5e9de", "explanation" : "Costa Rican Colon"},
    "HRK" : {"color" : "#d8c9c0", "explanation" : "Croatian Kuna"},
    "CUP" : {"color" : "#ccd2d4", "explanation" : "Cuban Peso"},
    "CZK" : {"color" : "#c8b1a2", "explanation" : "Czech Koruna"},
    "DKK" : {"color" : "#dbe4cc", "explanation" : "Danish Kroner"},
    "DJF" : {"color" : "#b387a3", "explanation" : "Dijiboutian Franc"},
    "DOP" : {"color" : "#d3b8a1", "explanation" : "Dominican Peso"},
    "XCD" : {"color" : "#c69b87", "explanation" : "Eastern Caribbean Dollar"},
    "EGP" : {"color" : "#c5bcb4", "explanation" : "Egyptian Pounds"},
    "ERN" : {"color" : "#beb4a9", "explanation" : "Eritrean Nakfa"},
    "ETB" : {"color" : "#a0b092", "explanation" : "Ethiopia Birr"},
    "FKP" : {"color" : "#ae9f95", "explanation" : "Falkland Island Pound"},
    "FOK" : {"color" : "#c3bbae", "explanation" : "Faroese Krona"},
    "FJD" : {"color" : "#deac8a", "explanation" : "Fijian Dollar"},
    "GMD" : {"color" : "#d7c8bc", "explanation" : "Gambian Dalasi"},
    "GEL" : {"color" : "#d5c4d7", "explanation" : "Georgian Lari"},
    "GHS" : {"color" : "#bbc3c7", "explanation" : "Ghanaian Cedi"},
    "GIP" : {"color" : "#cfa597", "explanation" : "Gibraltar Pound"},
    "GTQ" : {"color" : "#9aacbf", "explanation" : "Guatemalan Quetzal"},
    "GGP" : {"color" : "#dbbdb0", "explanation" : "Guernsey Pound"},
    "GNF" : {"color" : "#b3c9d7", "explanation" : "Guinean Franc"},
    "GYD" : {"color" : "#8aa87e", "explanation" : "Guyanese Dollar"},
    "HTG" : {"color" : "#c4c5d3", "explanation" : "Haitian Gourde"},
    "HNL" : {"color" : "#e0ced8", "explanation" : "Honduran Lempira"},
    "HKD" : {"color" : "#dbc1b9", "explanation" : "Hong Kong Dollar"},
    "HUF" : {"color" : "#d6c1c0", "explanation" : "Hungarian Forint"},
    "ISK" : {"color" : "#c9cac5", "explanation" : "Icelandic Krona"},
    "INR" : {"color" : "#e6c1e6", "explanation" : "Indian Rupee"},
    "IDR" : {"color" : "#ca9f95", "explanation" : "Indonesian Rupiah"},
    "IRR" : {"color" : "#abb299", "explanation" : "Iranian Rial"},
    "IQD" : {"color" : "#c9a7a1", "explanation" : "Iraqi Dinar"},
    "ILS" : {"color" : "#f4edca", "explanation" : "Israeli Shekel"},
    "JMD" : {"color" : "#c5cac4", "explanation" : "Jamaican Dollar"},
    "JPY" : {"color" : "#cdba9b", "explanation" : "Japanese Yen"},
    "JOD" : {"color" : "#8ea4a6", "explanation" : "Jordanian Dinar"},
    "KZT" : {"color" : "#8a98ba", "explanation" : "Kazakhstani Tenge"},
    "KES" : {"color" : "#e5d8c8", "explanation" : "Kenyan Shilling"},
    "KWD" : {"color" : "#d6ccca", "explanation" : "Kuwaiti Dinar"},
    "KGS" : {"color" : "#7c898d", "explanation" : "Kyrgyzstani Som"},
    "LAK" : {"color" : "#d3d4cb", "explanation" : "Lao Kip"},
    "LBP" : {"color" : "#e9d7c4", "explanation" : "Lebanese Pound"},
    "LSL" : {"color" : "#d1b39a", "explanation" : "Lesotho Loti"},
    "LRD" : {"color" : "#93a58c", "explanation" : "Liberian Dollar"},
    "LYD" : {"color" : "#f1e7d2", "explanation" : "Libyan Dinar"},
    "MKD" : {"color" : "#c2907f", "explanation" : "Macedonian Denar"},
    "MGA" : {"color" : "#dfd7b2", "explanation" : "Malagasy Ariary"},
    "MWK" : {"color" : "#e1cf97", "explanation" : "Malawian Kwacha"},
    "MYR" : {"color" : "#dbd2e6", "explanation" : "Malaysian Ringitt"},
    "MVR" : {"color" : "#e6ba8c", "explanation" : "Maldivian Rufiyaa"},
    "MRU" : {"color" : "#929c9a", "explanation" : "Mauritanian Ouguiya"},
    "MUR" : {"color" : "#CBC9C6", "explanation" : "Mauritian Rupee"},
    "MXN" : {"color" : "#d9d3d3", "explanation" : "Mexican Peso"},
    "MDL" : {"color" : "#dbd2c4", "explanation" : "Moldovan Leu"},
    "MNT" : {"color" : "#c6c8b9", "explanation" : "Mongolian Tugrik"},
    "MAD" : {"color" : "#ccced3", "explanation" : "Moroccan Dirham"},
    "MZN" : {"color" : "#c2cab5", "explanation" : "Mozambican Metical"},
    "NAD" : {"color" : "#cab9b7", "explanation" : "Namibian Dollar"},
    "NPR" : {"color" : "#cec8c1", "explanation" : "Nepalese Rupee"},
    "ANG" : {"color" : "#ccae87", "explanation" : "Netherlands Antillean Guilder"},
    "TWD" : {"color" : "#a2afba", "explanation" : "New Taiwan Dollar"},
    "NIO" : {"color" : "#9fc1a2", "explanation" : "Nicaraguan Dollar"},
    "NGN" : {"color" : "#c7b7af", "explanation" : "Nigerian Naira"},
    "KPW" : {"color" : "#d4c2b9", "explanation" : "North Korean Won"},
    "NOK" : {"color" : "#87a9c9", "explanation" : "Norwegian Krone"},
    "OMR" : {"color" : "#c5c2b0", "explanation" : "Omani Rials"},
    "PKR" : {"color" : "#cbd3d7", "explanation" : "Pakistani Rupee"},
    "PGK" : {"color" : "#b0b49a", "explanation" : "Papua New Guinean Kina"},
    "PYG" : {"color" : "#c1cec1", "explanation" : "Paraguayan Guarani"},
    "PEN" : {"color" : "#bfcac0", "explanation" : "Peruvian Sol"},
    "PHP" : {"color" : "#bfc8c8", "explanation" : "Philippine Peso"},
    "PLN" : {"color" : "#c5ccb8", "explanation" : "Polish Zloty"},
    "QAR" : {"color" : "#D1CAC4", "explanation" : "Qatari Riyal"},
    "RON" : {"color" : "#a9b1b4", "explanation" : "Romanian Leu"},
    "RUB" : {"color" : "#c5ccda", "explanation" : "Russian Rubles"},
    "RWF" : {"color" : "#4d4348", "explanation" : "Rwandan Franc"},
    "SHP" : {"color" : "#d5c9b8", "explanation" : "Saint Helena Pound"},
    "WST" : {"color" : "#7a80ac", "explanation" : "Samoan Tala"},
    "STN" : {"color" : "#e6d3d5", "explanation" : "Sao Tome and Principe Dobra"},
    "SAR" : {"color" : "#d3c1b7", "explanation" : "Saudi Riyal"},
    "RSD" : {"color" : "#cac9c6", "explanation" : "Serbian Dinar"},
    "SCR" : {"color" : "#dbbe78", "explanation" : "Seychellois Rupee"},
    "SLL" : {"color" : "#b7c6b2", "explanation" : "Sierra Leonean Leone"},
    "SGD" : {"color" : "#d3dad9", "explanation" : "Singapore Dollars"},
    "SBD" : {"color" : "#d9c2a4", "explanation" : "Solomun Island Dollar"},
    "SOS" : {"color" : "#d5c3be", "explanation" : "Somali Shillings"},
    "ZAR" : {"color" : "#d28c60", "explanation" : "South African Rand"},
    "KRW" : {"color" : "#c1ab73", "explanation" : "South Korean Won"},
    "SSP" : {"color" : "#bac2c7", "explanation" : "South Sudanese Pound"},
    "LKR" : {"color" : "#c3ab80", "explanation" : "Sri Lankan Rupee"},
    "SDG" : {"color" : "#b9a9cd", "explanation" : "Sudanese Pound"},
    "SRD" : {"color" : "#dad7cc", "explanation" : "Surinamese Dollar"},
    "SZL" : {"color" : "#cbd7c7", "explanation" : "Swazi Lilangeni"},
    "SEK" : {"color" : "#c4d0be", "explanation" : "Swedish Krona"},
    "SYP" : {"color" : "#aa9db2", "explanation" : "Syrian Pound"},
    "TJS" : {"color" : "#dcdece", "explanation" : "Tajikistani Somoni"},
    "TZS" : {"color" : "#e9b4bb", "explanation" : "Tanzanian Shilling"},
    "THB" : {"color" : "#b7a092", "explanation" : "Thai Baht"},
    "TOP" : {"color" : "#d1d9a8", "explanation" : "Tongan Pa'anga"},
    "TTD" : {"color" : "#9bb6d7", "explanation" : "Trinidad and Tobago Dollar"},
    "TND" : {"color" : "#cad9ca", "explanation" : "Tunisian Dinars"},
    "TRY" : {"color" : "#ff2121", "explanation" : "Turkish Lira"},
    "TMT" : {"color" : "#adcad2", "explanation" : "Turkmen Manat"},
    "AED" : {"color" : "#cbc1c2", "explanation" : "UAE Dirhams"},
    "UGX" : {"color" : "#dbb063", "explanation" : "Ugandan Shilling"},
    "UAH" : {"color" : "#d3e0df", "explanation" : "Ukranian Hryvnia"},
    "UYU" : {"color" : "#dad8bb", "explanation" : "Uruguayan Peso"},
    "UZS" : {"color" : "#d0b4aa", "explanation" : "Uzbekistani Som"},
    "VES" : {"color" : "#dad1b6", "explanation" : "Venezuelan Bolivar"},
    "VND" : {"color" : "#bdbdb7", "explanation" : "Vietnamese Dong"},
    "XOF" : {"color" : "#c5b9c9", "explanation" : "West African Franc"},
    "YER" : {"color" : "#b8bd9d", "explanation" : "Yemen Rial"},
    "ZMW" : {"color" : "#d2d2b7", "explanation" : "Zambian Kwacha"},


    //Grave of Pablo Picasso
    "USD" : {"color" : "#6B9937", "explanation" : "USD"},
    "EUR" : {"color" : "#46BDE6", "explanation" : "Euro"},
    "GBP" : {"color" : "#D25CE6", "explanation" : "Pound Sterling"},

    "CAD" : {"color" : "#3BF04D", "explanation" : "Canadian Dollar"},
    "CHF" : {"color" : "#F02466", "explanation" : "Swiss Franc"},
    "NZD" : {"color" : "#547CF0", "explanation" : "New Zealand Dollar"},
}